# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.10
    commands:
      - echo pre Installing ..........
  pre_build:
    commands:
      - echo prebuild,Installing update .......
      # 基本环境更新
      #- yum update -y
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - ls
      - mkdir build
      - # 替换所有尖括号标注，替换时，去掉尖括号
      - CurrentVersion=$(echo $(aws lambda get-alias --function-name arn:aws:lambda:ap-northeast-2:043942809940:function:test_lambda_function --name test_lambda_function --region ap-northeast-2 | grep FunctionVersion | tail -1 |tr -cd "[0-9]"))
      - zip -r ./build/lambda.zip ./lambda_function.py
      - aws lambda update-function-code --function-name arn:aws:lambda:ap-northeast-2:043942809940:function:test_lambda_function --zip-file fileb://build/lambda.zip  --region ap-northeast-2 --publish
      - TargetVersion=$(echo $(aws lambda list-versions-by-function --function-name arn:aws:lambda:ap-northeast-2:043942809940:function:test_lambda_function --region ap-northeast-2 | grep Version | tail -1 | tr -cd "[0-9]"))
      - echo $CurrentVersion
      - echo $TargetVersion
      - sed -e 's/{{CurrentVersion}}/'$CurrentVersion'/g' -e 's/{{TargetVersion}}/'$TargetVersion'/g' appspec.template.yaml > appspec.yaml
      - aws s3 cp appspec.yaml s3://aws-jenkins-codepipeline/codedeploy/appspec.yaml
      - aws deploy create-deployment --application-name github_codedeploy --deployment-group-name deploy_group --s3-location bucket='aws-jenkins-codepipeline',key='codedeploy/appspec.yaml',bundleType=YAML
artifacts:
  type: yaml
  files:
    - appspec.yaml
